
[phases.install]
cmds = [
  "npm install",
  "npm install --prefix client",
  "npm install --prefix server"
]

[phases.build]
cmds = [
  "npm run build --prefix client",
  "cd server && npx prisma generate --schema=prisma/schema.prisma --config=prisma.config.ts"
]

[start]
cmd = "node server/index.js"
